<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="37067" started-at="2017-08-10T19:06:10Z" finished-at="2017-08-10T19:06:47Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="37067" started-at="2017-08-10T19:06:10Z" finished-at="2017-08-10T19:06:47Z">
      <class name="com.automation.testScripts.TC_AddingTask">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.automation.testScripts.TC_AddingTask@5792a0]" name="setUp" is-config="true" duration-ms="36768" started-at="2017-08-10T12:06:10Z" finished-at="2017-08-10T12:06:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="EnterTask()[pri:0, instance:com.automation.testScripts.TC_AddingTask@5792a0]" name="EnterTask" duration-ms="0" started-at="2017-08-10T12:06:47Z" data-provider="enterTask" finished-at="2017-08-10T12:06:47Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void com.automation.testScripts.TC_AddingTask.EnterTask() requires a @DataProvider named : enterTask]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void com.automation.testScripts.TC_AddingTask.EnterTask() requires a @DataProvider named : enterTask
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:336)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:498)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1293)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1020)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1110)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EnterTask -->
        <test-method status="FAIL" signature="EnterMultipleTasks()[pri:2, instance:com.automation.testScripts.TC_AddingTask@5792a0]" name="EnterMultipleTasks" duration-ms="0" started-at="2017-08-10T12:06:47Z" data-provider="enterTask" finished-at="2017-08-10T12:06:47Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void com.automation.testScripts.TC_AddingTask.EnterMultipleTasks() requires a @DataProvider named : enterTask]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void com.automation.testScripts.TC_AddingTask.EnterMultipleTasks() requires a @DataProvider named : enterTask
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:336)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:498)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1293)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1020)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1110)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EnterMultipleTasks -->
        <test-method status="PASS" signature="quitBrowser()[pri:0, instance:com.automation.testScripts.TC_AddingTask@5792a0]" name="quitBrowser" is-config="true" duration-ms="1" started-at="2017-08-10T12:06:47Z" finished-at="2017-08-10T12:06:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
      </class> <!-- com.automation.testScripts.TC_AddingTask -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
